name:                NaiveSolver
version:             0.1.0.0
github:              "githubuser/NaiveSolver"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/NaiveSolver#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- QuickCheck
- generic-random
- transformers
- text
- ghc-prim
- vector
- prettyprinter
- kure
- lens
- hashable
- bytestring
- primitive
- unordered-containers
- vector-hashtables
- generic-lens
- profunctors
- distributive
- pretty-simple
# - express
# - speculate
# - extrapolate
# - leancheck
- indexed
- quickspec
- twee-lib
- zippers
- mmorph
- foldl
- deepseq
- PyF
- spoon
- StrictCheck
- generics-sop
- monad-control
- generic-lens-core
- overeasy
- int-like >= 0.1 && < 0.2
- recursion-schemes
- unordered-containers
- data-fix
# - uniter
library:
  source-dirs: src
ghc-options:
    - -Wall -Wunused-dependencies
    - -O2
default-extensions: GHC2021

executables:
  NaiveSolver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - NaiveSolver

tests:
  NaiveSolver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NaiveSolver
